### ISSUE TITLE
Postmark InvalidMessageError when trying to email and delete Hit data

### ISSUE THREAD

**Issue by rynkwn** [rynkwn/rblog#117]
```
Completed 500 Internal Server Error in 525ms (ActiveRecord: 27.6ms)
2016-04-25T03:26:48.024397+00:00 app[web.1]: Postmark::InvalidMessageError (Received valid, but incompatible JSON input.):
2016-04-25T03:26:48.024398+00:00 app[web.1]:   app/mailers/bloghistory.rb:15:in `analytics_email'
2016-04-25T03:26:48.024399+00:00 app[web.1]:   app/controllers/main_pages_controller.rb:100:in `analytics_send_data'
2016-04-25T03:26:48.024399+00:00 app[web.1]: 
```

**Comment by rynkwn** [comment]
Done with newest commit
